
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Connection.ConnectionProvider;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class ClassPayment extends javax.swing.JFrame {

    public void TableDetails()
    {
        DefaultTableModel dtm=(DefaultTableModel)jTableFee.getModel();
        dtm.setRowCount(0);
        String id=jTextFieldStId.getText();
        try{
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from fee where id='"+id+"'");
            while(rs.next())
            {
                dtm.addRow(new Object[]{rs.getString(2),rs.getString(3)});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void date()
    {
        SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        String month=df.format(date);
        jLabelDate2.setText(month);
    }
    
    public ClassPayment() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnClose = new javax.swing.JButton();
        jlblPayment = new javax.swing.JLabel();
        jBtnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblStid = new javax.swing.JLabel();
        jTextFieldStId = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        jLabelDate2 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelMN = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelFee = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldMN = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldFee = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFee = new javax.swing.JTable();
        jLabelBCKG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jBtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_48px.png"))); // NOI18N
        jBtnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jlblPayment.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlblPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bank_40px.png"))); // NOI18N
        jlblPayment.setText("Payment");

        jBtnHome.setBackground(new java.awt.Color(255, 153, 0));
        jBtnHome.setForeground(new java.awt.Color(255, 153, 0));
        jBtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/home_24px.png"))); // NOI18N
        jBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlblPayment)
                .addGap(300, 300, 300)
                .addComponent(jBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPayment))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblStid.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlblStid.setText("Student ID: ");
        jPanel2.add(jlblStid, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 45, -1, -1));

        jTextFieldStId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jTextFieldStId, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 46, 59, -1));

        jBtnSearch.setBackground(new java.awt.Color(255, 255, 51));
        jBtnSearch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_16px.png"))); // NOI18N
        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 43, -1, -1));

        jLabelDate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelDate.setText("Date");
        jPanel2.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 111, -1, -1));

        jLabelDate2.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        jLabelDate2.setText("mm-dd-yy");
        jPanel2.add(jLabelDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 111, -1, -1));

        jLabelName.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelName.setText("Name");
        jLabelName.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelNameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 150, -1, -1));

        jLabelMN.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelMN.setText("Mobile Number");
        jPanel2.add(jLabelMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 215, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelEmail.setText("Email");
        jPanel2.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 280, -1, -1));

        jLabelFee.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelFee.setText("Month / Fee");
        jPanel2.add(jLabelFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 345, -1, -1));

        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 182, 384, -1));

        jTextFieldMN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jTextFieldMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 247, 384, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 312, 384, -1));

        jTextFieldFee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jTextFieldFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 377, 384, -1));

        jButtonSave.setBackground(new java.awt.Color(255, 255, 51));
        jButtonSave.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_26px_1.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 447, 129, -1));

        jButtonReset.setBackground(new java.awt.Color(255, 255, 51));
        jButtonReset.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 447, 135, -1));

        jTableFee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Fee"
            }
        ));
        jScrollPane1.setViewportView(jTableFee);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 43, -1, 386));

        jLabelBCKG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBCKG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/b5.jpg"))); // NOI18N
        jLabelBCKG.setText("jLabel9");
        jPanel2.add(jLabelBCKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1070, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ClassPayment().setVisible(true);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        // TODO add your handling code here:
        TableDetails();
        int checkid=0;
        String id=jTextFieldStId.getText();
        String month=jLabelDate2.getText();
        try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student where id='"+id+"'");
            while(rs.next())
            {
                checkid=1;
                jTextFieldStId.setEditable(false);
                jTextFieldName.setText(rs.getString(2));
                jTextFieldMN.setText(rs.getString(4));
                jTextFieldEmail.setText(rs.getString(5));
            }
            
            if(checkid==1)
            {
                
                ResultSet rs1=st.executeQuery("select * from fee inner join student where fee.month='"+month+"' and fee.id='"+id+"' and student.id='"+id+"'");
                while(rs1.next())
                {
                    jButtonSave.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Payment is already done for this Month");
                }
            }
            else
            {
              JOptionPane.showMessageDialog(null, "Student ID does not Exist");
           }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String id=jTextFieldStId.getText();
        String month=jLabelDate2.getText();
        String fee=jTextFieldFee.getText();
        try
        {
            Connection con=ConnectionProvider.getcon();
            PreparedStatement ps=con.prepareStatement("insert into fee values(?,?,?)");
            ps.setString(1, id);
            ps.setString(2, month);
            ps.setString(3, fee);
            ps.executeUpdate();
            TableDetails();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new ClassPayment().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHomeActionPerformed
        // TODO add your handling code here:
        Dashboard hm = new Dashboard();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnHomeActionPerformed

    private void jLabelNameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelNameAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNameAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnHome;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelBCKG;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDate2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFee;
    private javax.swing.JLabel jLabelMN;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFee;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFee;
    private javax.swing.JTextField jTextFieldMN;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldStId;
    private javax.swing.JLabel jlblPayment;
    private javax.swing.JLabel jlblStid;
    // End of variables declaration//GEN-END:variables
}
