
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Dashboard() {
        initComponents();
          Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnADD = new javax.swing.JButton();
        jButtonUpDlt = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButtonSFees = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLB1 = new javax.swing.JLabel();
        jLB2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnADD.setBackground(new java.awt.Color(102, 102, 255));
        jBtnADD.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jBtnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user_male_40px.png"))); // NOI18N
        jBtnADD.setText("ADD New Students");
        jBtnADD.setBorder(null);
        jBtnADD.setIconTextGap(6);
        jBtnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnADDActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 57, 230, 40));

        jButtonUpDlt.setBackground(new java.awt.Color(102, 102, 255));
        jButtonUpDlt.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jButtonUpDlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        jButtonUpDlt.setText("Update & Delete Students");
        jButtonUpDlt.setBorder(null);
        jButtonUpDlt.setIconTextGap(6);
        jButtonUpDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpDltActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpDlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 129, 230, 40));

        jButtonList.setBackground(new java.awt.Color(102, 102, 255));
        jButtonList.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jButtonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list_of_thumbnails_30px.png"))); // NOI18N
        jButtonList.setText("List Of Students");
        jButtonList.setBorder(null);
        jButtonList.setIconTextGap(8);
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonList, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 204, 230, 40));

        jButtonSFees.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSFees.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jButtonSFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money_32px.png"))); // NOI18N
        jButtonSFees.setText("Student Fees");
        jButtonSFees.setBorder(null);
        jButtonSFees.setIconTextGap(8);
        jButtonSFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSFeesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 289, 230, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_48px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 2, 38, 32));

        jLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/back2.png"))); // NOI18N
        jLB1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 310, 330));

        jLB2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/B4.jpg"))); // NOI18N
        jPanel1.add(jLB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 890, 390));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnADDActionPerformed
        // TODO add your handling code here:
        new StRegistrarion().setVisible(true);
    }//GEN-LAST:event_jBtnADDActionPerformed

    private void jButtonUpDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpDltActionPerformed
        // TODO add your handling code here:
         new ManageStData().setVisible(true);
    }//GEN-LAST:event_jButtonUpDltActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
        // TODO add your handling code here:
        new ShowStData().setVisible(true);
    }//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonSFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSFeesActionPerformed
        // TODO add your handling code here:
         new ClassPayment().setVisible(true);
    }//GEN-LAST:event_jButtonSFeesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to Exit Application?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnADD;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonList;
    private javax.swing.JButton jButtonSFees;
    private javax.swing.JButton jButtonUpDlt;
    private javax.swing.JLabel jLB1;
    private javax.swing.JLabel jLB2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
