
import java.awt.Dimension;
import java.awt.Toolkit;
import Connection.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;


public class StRegistrarion extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public StRegistrarion() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        try
        {
            int id=1;
            String str=String.valueOf(id);
            jLabelStIdC.setText(str);
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select max(id) from student");
            while(rs.next())
            {
                id=rs.getInt(1);
                id+=1;
                String str1=String.valueOf(id);
                jLabelStIdC.setText(str1);
            
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jLabelStADD = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelStId = new javax.swing.JLabel();
        jLabelStIdC = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelMN = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldMN = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldNIC = new javax.swing.JTextField();
        jLabelNIC = new javax.swing.JLabel();
        jLabelRFee = new javax.swing.JLabel();
        jTextFieldRFee = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLbBCKG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClose.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_48px.png"))); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 0, 30, 30));

        jLabelStADD.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabelStADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user_male_40px.png"))); // NOI18N
        jLabelStADD.setText("ADD New Student");
        jPanel1.add(jLabelStADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jButtonHome.setBackground(new java.awt.Color(255, 153, 0));
        jButtonHome.setForeground(new java.awt.Color(255, 153, 0));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/home_24px.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 50, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabelStId.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelStId.setText("Student ID :");
        jPanel2.add(jLabelStId);
        jLabelStId.setBounds(75, 28, 84, 21);

        jLabelStIdC.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelStIdC.setText("00");
        jPanel2.add(jLabelStIdC);
        jLabelStIdC.setBounds(177, 28, 18, 21);

        jLabelName.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelName.setText("Name");
        jPanel2.add(jLabelName);
        jLabelName.setBounds(75, 82, 49, 21);

        jLabelMN.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelMN.setText("Mobile Number");
        jPanel2.add(jLabelMN);
        jLabelMN.setBounds(75, 336, 121, 21);

        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldName);
        jTextFieldName.setBounds(75, 121, 380, 26);

        jTextFieldMN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldMN);
        jTextFieldMN.setBounds(75, 375, 380, 26);

        jLabelEmail.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelEmail.setText("Email");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(75, 257, 43, 21);

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(75, 284, 380, 26);

        jLabelGender.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelGender.setText("Gender");
        jPanel2.add(jLabelGender);
        jLabelGender.setBounds(550, 82, 59, 21);

        jComboBoxGender.setBackground(new java.awt.Color(204, 255, 204));
        jComboBoxGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(jComboBoxGender);
        jComboBoxGender.setBounds(550, 121, 380, 26);

        jLabelAge.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelAge.setText("Age");
        jPanel2.add(jLabelAge);
        jLabelAge.setBounds(550, 171, 33, 21);

        jTextFieldAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldAge);
        jTextFieldAge.setBounds(550, 198, 380, 26);

        jTextFieldNIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldNIC);
        jTextFieldNIC.setBounds(75, 198, 380, 26);

        jLabelNIC.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelNIC.setText("NIC");
        jPanel2.add(jLabelNIC);
        jLabelNIC.setBounds(75, 171, 28, 21);

        jLabelRFee.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelRFee.setText("Registration Fee");
        jPanel2.add(jLabelRFee);
        jLabelRFee.setBounds(550, 257, 130, 21);

        jTextFieldRFee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldRFee);
        jTextFieldRFee.setBounds(550, 284, 380, 26);

        jButtonSave.setBackground(new java.awt.Color(255, 204, 0));
        jButtonSave.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_26px.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSave);
        jButtonSave.setBounds(75, 448, 111, 35);

        jButtonReset.setBackground(new java.awt.Color(255, 204, 0));
        jButtonReset.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset);
        jButtonReset.setBounds(280, 448, 119, 35);

        jLbBCKG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbBCKG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/b5.jpg"))); // NOI18N
        jLbBCKG.setText("jlb");
        jPanel2.add(jLbBCKG);
        jLbBCKG.setBounds(0, -9, 1100, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new StRegistrarion().setVisible(true);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String id=jLabelStIdC.getText();
        String name=jTextFieldName.getText();
        String mobilenumber=jTextFieldMN.getText();
        String email=jTextFieldEmail.getText();
        String gender=(String)jComboBoxGender.getSelectedItem();
        String age=jTextFieldAge.getText();
        String nic=jTextFieldNIC.getText();
        String fee=jTextFieldRFee.getText();
        
        try
        {
            Connection con=ConnectionProvider.getcon();
            PreparedStatement ps=con.prepareStatement("insert into student values (?,?,?,?,?,?,?,?)");
            ps.setString(1, id);
            ps.setString(2, name);
            ps.setString(3, nic);
            ps.setString(4, mobilenumber);
            ps.setString(5, email);
            ps.setString(6, gender);
            ps.setString(7, age);
            ps.setString(8, fee);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Saved");
            setVisible(false);
            new StRegistrarion().setVisible(true);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
          Dashboard hm = new Dashboard();
          hm.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StRegistrarion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StRegistrarion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StRegistrarion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StRegistrarion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StRegistrarion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelMN;
    private javax.swing.JLabel jLabelNIC;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRFee;
    private javax.swing.JLabel jLabelStADD;
    private javax.swing.JLabel jLabelStId;
    private javax.swing.JLabel jLabelStIdC;
    private javax.swing.JLabel jLbBCKG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMN;
    private javax.swing.JTextField jTextFieldNIC;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldRFee;
    // End of variables declaration//GEN-END:variables
}
