
import javax.swing.*;
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public UserLogin() {
        initComponents();
        jLabelError.setVisible(false);
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jlblSMS = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jTextFieldUName = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonLOGIN = new javax.swing.JButton();
        jCheckBoxSPass = new javax.swing.JCheckBox();
        jLabelUName = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelUPF = new javax.swing.JLabel();
        jLB3 = new javax.swing.JLabel();
        jLB2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(225, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClose.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_32px.png"))); // NOI18N
        jButtonClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jButtonClose.setBorderPainted(false);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 0, 31, 31));

        jlblSMS.setBackground(new java.awt.Color(255, 255, 255));
        jlblSMS.setFont(new java.awt.Font("Iskoola Pota", 1, 50)); // NOI18N
        jlblSMS.setText("       Students  Mangement System");
        getContentPane().add(jlblSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 114));

        jLabelError.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_16px.png"))); // NOI18N
        jLabelError.setText("Incorrect Username Or Password");
        getContentPane().add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 290, 25));

        jTextFieldUName.setBackground(new java.awt.Color(153, 153, 255));
        jTextFieldUName.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jTextFieldUName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUNameFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 256, -1));

        jPasswordFieldPass.setBackground(new java.awt.Color(153, 153, 255));
        jPasswordFieldPass.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jPasswordFieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPassFocusLost(evt);
            }
        });
        getContentPane().add(jPasswordFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 256, -1));

        jButtonLOGIN.setBackground(new java.awt.Color(51, 102, 255));
        jButtonLOGIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLOGIN.setText("LOGIN");
        jButtonLOGIN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGINActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 442, 130, 50));

        jCheckBoxSPass.setBackground(new java.awt.Color(0, 102, 204));
        jCheckBoxSPass.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jCheckBoxSPass.setText("Show Password");
        jCheckBoxSPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSPassActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxSPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 360, 170, -1));

        jLabelUName.setFont(new java.awt.Font("Iskoola Pota", 3, 20)); // NOI18N
        jLabelUName.setText("Username");
        getContentPane().add(jLabelUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 100, 25));

        jLabelPass.setFont(new java.awt.Font("Iskoola Pota", 3, 20)); // NOI18N
        jLabelPass.setText("Password");
        getContentPane().add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 89, 23));

        jLabelUPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/B4.jpg"))); // NOI18N
        jLabelUPF.setText("jLabel1");
        getContentPane().add(jLabelUPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 800, 240));

        jLB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/back2.png"))); // NOI18N
        jLB3.setText("jLabel5");
        getContentPane().add(jLB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 800, 160));

        jLB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/back2.png"))); // NOI18N
        jLB2.setText("jLabel5");
        getContentPane().add(jLB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUNameFocusGained
        // TODO add your handling code here:
        jLabelError.setVisible(false);
        if(jTextFieldUName.getText().equals("Enter Username")){
            jTextFieldUName.setText("");
        }
    }//GEN-LAST:event_jTextFieldUNameFocusGained

    private void jTextFieldUNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUNameFocusLost
        // TODO add your handling code here:
        jLabelError.setVisible(false);
        if(jTextFieldUName.getText().equals("")){
            jTextFieldUName.setText("Enter Username");
        }
    }//GEN-LAST:event_jTextFieldUNameFocusLost

    private void jPasswordFieldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPassFocusGained
        // TODO add your handling code here:
        jLabelError.setVisible(false);
        if(jPasswordFieldPass.getText().equals("Enter Password")){
            jPasswordFieldPass.setText("");
        }
    }//GEN-LAST:event_jPasswordFieldPassFocusGained

    private void jPasswordFieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPassFocusLost
        // TODO add your handling code here:
        jLabelError.setVisible(false);
        if(jPasswordFieldPass.getText().equals("")){
            jPasswordFieldPass.setText("Enter Password");
        }
    }//GEN-LAST:event_jPasswordFieldPassFocusLost

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to Exit Application?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGINActionPerformed
        // TODO add your handling code here:
        if(jTextFieldUName.getText().equals("admin") && jPasswordFieldPass.getText().equals("1234")){
            setVisible(false);
            new Dashboard().setVisible(true);
        }
        else{
            jLabelError.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLOGINActionPerformed

    private void jCheckBoxSPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSPassActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxSPass.isSelected()){
            jPasswordFieldPass.setEchoChar((char)0);
        }
        else{
            jPasswordFieldPass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxSPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLOGIN;
    private javax.swing.JCheckBox jCheckBoxSPass;
    private javax.swing.JLabel jLB2;
    private javax.swing.JLabel jLB3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUName;
    private javax.swing.JLabel jLabelUPF;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldUName;
    private javax.swing.JLabel jlblSMS;
    // End of variables declaration//GEN-END:variables
}
